import { useEffect, useState } from "react";
import { Bell, BriefcaseBusiness, Building2, ClipboardList, GraduationCap, MessageSquare, ShieldCheck, Star, UserCheck } from "lucide-react";
import { Link } from "react-router-dom";
import Alert from "../../components/common/Alert";
import Button from "../../components/common/Button";
import Spinner from "../../components/common/Spinner";
import AppHeader from "../../components/layout/AppHeader";
import WorkspaceStatCard from "../../components/workspace/WorkspaceStatCard";
import { dashboardService } from "../../services/dashboardService";
import { getApiError } from "../../utils/apiError";
import { formatJobDate } from "../../utils/jobOptions";

export default function AdminDashboardPage() {
  const [retry, setRetry] = useState(0);
  const [state, setState] = useState({ status: "loading", data: null, error: "" });
  useEffect(() => { let active = true; dashboardService.getAdminDashboard().then((data) => active && setState({ status: "success", data, error: "" })).catch((error) => active && setState({ status: "error", data: null, error: getApiError(error).message })); return () => { active = false; }; }, [retry]);
  return <div className="min-h-screen bg-surface"><AppHeader /><main className="page-container py-9 sm:py-12"><span className="eyebrow"><ShieldCheck className="size-3.5" aria-hidden="true" />Administration</span><h1 className="mt-4 text-4xl font-extrabold tracking-[-0.05em] text-ink-950">Admin Dashboard</h1><p className="mt-3 text-ink-600">Authoritative platform health, lifecycle totals, and recent administrative activity.</p>{state.status === "loading" ? <Spinner label="Loading Admin dashboard…" /> : null}{state.status === "error" ? <div className="surface-card mt-8 p-6"><Alert>{state.error}</Alert><Button className="mt-5" onClick={() => setRetry((value) => value + 1)}>Try again</Button></div> : null}{state.data ? <AdminSummary {...state.data} /> : null}</main></div>;
}

export function AdminSummary({ summary, statistics, recentAudits = [] }) {
  if (!statistics) return <LegacySummary summary={summary} />;
  const applicationItems = Object.entries(statistics.applications || {}).map(([label, value]) => ({ label, value }));
  return <><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Admin account summary"><WorkspaceStatCard label="Students" value={statistics.accounts.students.total} icon={GraduationCap} /><WorkspaceStatCard label="Approved Students" value={statistics.accounts.students.approved} icon={UserCheck} tone="emerald" /><WorkspaceStatCard label="Job Providers" value={statistics.accounts.providers.total} icon={Building2} tone="blue" /><WorkspaceStatCard label="Pending Registrations" value={summary.pendingRegistrations} icon={UserCheck} tone="amber" /></section><DashboardGroup title="Account states" icon={GraduationCap} items={[{ label: "Student pending", value: statistics.accounts.students.pending }, { label: "Student rejected", value: statistics.accounts.students.rejected }, { label: "Student suspended", value: statistics.accounts.students.suspended }, { label: "Provider approved", value: statistics.accounts.providers.approved }, { label: "Provider pending", value: statistics.accounts.providers.pending }, { label: "Provider rejected", value: statistics.accounts.providers.rejected }, { label: "Provider suspended", value: statistics.accounts.providers.suspended }]} /><DashboardGroup title="Jobs" icon={BriefcaseBusiness} items={Object.entries(statistics.jobs).map(([label, value]) => ({ label, value }))} /><DashboardGroup title="Applications" icon={ClipboardList} items={applicationItems} /><div className="mt-8 grid gap-6 lg:grid-cols-2"><DashboardGroup compact title="Reviews" icon={Star} items={Object.entries(statistics.reviews).map(([label, value]) => ({ label, value }))} /><DashboardGroup compact title="Communication totals" icon={MessageSquare} items={[{ label: "Messages (count only)", value: statistics.communication.messages }, { label: "Notifications", value: statistics.communication.notifications }]} /></div><section className="surface-card mt-8 flex flex-col gap-5 p-6 sm:flex-row sm:items-center sm:justify-between sm:p-8"><div><h2 className="text-2xl font-extrabold text-ink-950">Registration queue</h2><p className="mt-2 text-sm leading-6 text-ink-600">{summary.pendingStudents} Student and {summary.pendingProviders} Job Provider registrations await review.</p></div><Button as={Link} to="/admin/registrations">Review {summary.pendingRegistrations} pending</Button></section><AuditActivity audits={recentAudits} /></>;
}

function LegacySummary({ summary }) { return <><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><WorkspaceStatCard label="Pending Registrations" value={summary.pendingRegistrations} icon={UserCheck} tone="amber" /><WorkspaceStatCard label="Students" value={summary.totalStudents} icon={GraduationCap} /><WorkspaceStatCard label="Job Providers" value={summary.totalProviders} icon={Building2} tone="blue" /><WorkspaceStatCard label="Open Jobs" value={summary.openJobs} icon={BriefcaseBusiness} tone="emerald" /></section><Button as={Link} to="/admin/registrations" className="mt-6">Review Registrations</Button></>; }
function DashboardGroup({ title, icon: Icon, items, compact = false }) { return <section className={`surface-card ${compact ? "p-6" : "mt-8 p-6 sm:p-8"}`}><h2 className="flex items-center gap-2 text-xl font-extrabold text-ink-950"><Icon className="size-5 text-brand-600" aria-hidden="true" />{title}</h2><dl className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-4">{items.map(({ label, value }) => <div key={label} className="rounded-2xl bg-slate-50 p-4"><dt className="text-xs font-bold text-ink-500 capitalize">{label}</dt><dd className="mt-1 text-2xl font-extrabold text-ink-950">{value}</dd></div>)}</dl></section>; }
function AuditActivity({ audits }) { return <section className="surface-card mt-8 p-6 sm:p-8"><div className="flex items-center justify-between gap-4"><h2 className="flex items-center gap-2 text-xl font-extrabold text-ink-950"><Bell className="size-5 text-brand-600" aria-hidden="true" />Recent Admin activity</h2><Button as={Link} to="/admin/settings#activity" variant="secondary">View audit trail</Button></div>{audits.length ? <ol className="mt-5 grid gap-3">{audits.map((audit) => <li key={audit.id} className="rounded-2xl border border-slate-200 p-4"><p className="text-sm font-extrabold text-ink-900">{audit.action.replaceAll("_", " ")}</p><p className="mt-1 break-words text-xs text-ink-500">{audit.entityType} · {audit.entityId} · {formatJobDate(audit.createdAt)}</p></li>)}</ol> : <p className="mt-5 text-sm text-ink-600">No administrative actions have been recorded yet.</p>}</section>; }
